# Generated by Django 4.2.3 on 2023-08-25 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0003_userprofile_delete_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progress",
            old_name="exercises_completed",
            new_name="energyPoints",
        ),
    ]
